### PR TITLE
Add a fixer for django.conf.urls deprecations

### PR DESCRIPTION
**Pull request by matthiask**
This fixer doesn't work yet. It somehow doesn't replace `django.conf.urls.url` with `django.urls.re_path`, only with `django.urls.url`.

That's a bit sad. I'm still posting it here. This fixer would make my life so much easier. Thanks :)

### CODE REVIEW

**Comment by adamchainz** [comment]
There's prior art to copy from django-codemod here, which rewrites `url()` calls to `path()` if it can: https://github.com/browniebroke/django-codemod/blob/main/django_codemod/visitors/urls.py

**Comment by matthiask** [comment]
> 
> 
> There's prior art to copy from django-codemod here, which rewrites `url()` calls to `path()` if it can: https://github.com/browniebroke/django-codemod/blob/main/django_codemod/visitors/urls.py

Ah yes, that would be nice too. However, it probbly has a lower priority since `re_path` won't go away soon? (I agree that `path` is nicer but old habits...)

**Comment by adamchainz** [comment]
I don't really want to add a `url` -> `re_path` rewriter when there's the better fixer to adapt. It shouldn't be too much extra work. I even started a branch for this locally already but didn't have time to finish it.

**Comment by adamchainz** [comment]
Superceded by #57, thanks for the initial PR.

**Pull request closed without merging**
