### PR TITLE
Rewrite django.utils.timezone.utc to datetime.timezone.utc

### PR DESCRIPTION
**Pull request by hramezani**
Fixes https://github.com/adamchainz/django-upgrade/issues/135

### CODE REVIEW

**Comment by adamchainz** [comment]
Brilliant work, thank you!

**Comment by adamchainz** [comment]
Released in 1.8.0!

**Comment by valberg** [comment]
Small nitpick: HISTORY.rst refers to #140 not #169 :)

**Comment by hramezani** [comment]
> Small nitpick: HISTORY.rst refers to #140 not #169 :)

Thanks @valberg for finding this. I will prepare a fix PR soon

**Pull request merged**
